from __future__ import annotations

"""Frozen schema snapshot used by the Alembic baseline revision.

Do not mutate this module when adding future schema changes. New changes belong
in new Alembic revisions.
"""

from sqlalchemy import (
    Boolean,
    CheckConstraint,
    Column,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    MetaData,
    String,
    Table,
    Text,
    text,
)

metadata = MetaData()

categories = Table(
    "categories",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("name", String, nullable=False, unique=True),
    Index("ix_categories_id", "id"),
    Index("ix_categories_name", "name", unique=True),
)

users = Table(
    "users",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("first_name", String, nullable=False),
    Column("last_name", String, nullable=False),
    Column("email", String, nullable=False, unique=True),
    Column("dni", String, nullable=True),
    Column("phone", String, nullable=True),
    Column("password_hash", String, nullable=False),
    Column("has_account", Boolean, nullable=False),
    Column("token_version", Integer, nullable=False),
    Column("is_admin", Boolean, nullable=False),
    Column("email_verified_at", DateTime(timezone=True), nullable=True),
    Column("email_verification_sent_at", DateTime(timezone=True), nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Index("ix_users_id", "id"),
    Index("ix_users_email", "email", unique=True),
    Index("ix_users_dni", "dni"),
)

auth_login_throttles = Table(
    "auth_login_throttles",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("scope", String, nullable=False),
    Column("key", String, nullable=False),
    Column("failed_count", Integer, nullable=False),
    Column("window_started_at", DateTime(timezone=True), nullable=False),
    Column("blocked_until", DateTime(timezone=True), nullable=True),
    Column("updated_at", DateTime(timezone=True), nullable=False),
    CheckConstraint("failed_count >= 0", name="ck_auth_login_throttles_failed_count_non_negative"),
    Index("ix_auth_login_throttles_id", "id"),
    Index("ix_auth_login_throttles_scope", "scope"),
    Index("ix_auth_login_throttles_key", "key"),
    Index("ix_auth_login_throttles_blocked_until", "blocked_until"),
    Index("uq_auth_login_throttles_scope_key", "scope", "key", unique=True),
)

idempotency_records = Table(
    "idempotency_records",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("scope", String, nullable=False),
    Column("idempotency_key", String, nullable=False),
    Column("request_hash", String, nullable=False),
    Column("response_payload", Text, nullable=False),
    Column("status", String, nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("expires_at", DateTime(timezone=True), nullable=False),
    Index("ix_idempotency_records_id", "id"),
    Index("ix_idempotency_records_scope", "scope"),
    Index("ix_idempotency_records_idempotency_key", "idempotency_key"),
    Index("uq_idempotency_records_scope_key", "scope", "idempotency_key", unique=True),
    Index("ix_idempotency_records_expires_at", "expires_at"),
)

products = Table(
    "products",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("name", String, nullable=False),
    Column("description", String, nullable=True),
    Column("img_url", String, nullable=True),
    Column("category_id", Integer, ForeignKey("categories.id", ondelete="RESTRICT"), nullable=False),
    Index("ix_products_id", "id"),
)

discounts = Table(
    "discounts",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("name", String, nullable=False),
    Column("type", String, nullable=False),
    Column("value", Integer, nullable=False),
    Column("scope", String, nullable=False),
    Column("category_id", Integer, ForeignKey("categories.id", ondelete="SET NULL"), nullable=True),
    Column("product_id", Integer, ForeignKey("products.id", ondelete="SET NULL"), nullable=True),
    Column("is_active", Boolean, nullable=False),
    Column("starts_at", DateTime(timezone=True), nullable=True),
    Column("ends_at", DateTime(timezone=True), nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
    CheckConstraint("value > 0", name="ck_discounts_value_positive"),
    CheckConstraint(
        "((scope = 'all' AND category_id IS NULL AND product_id IS NULL) OR "
        "(scope = 'category' AND category_id IS NOT NULL AND product_id IS NULL) OR "
        "(scope = 'product' AND category_id IS NULL AND product_id IS NOT NULL) OR "
        "(scope = 'product_list' AND category_id IS NULL AND product_id IS NULL))",
        name="ck_discounts_scope_target_consistency",
    ),
    Index("ix_discounts_id", "id"),
    Index("ix_discounts_category_id", "category_id"),
    Index("ix_discounts_product_id", "product_id"),
)

product_variants = Table(
    "product_variants",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("product_id", Integer, ForeignKey("products.id", ondelete="CASCADE"), nullable=False),
    Column("sku", String, nullable=False, unique=True),
    Column("size", String, nullable=True),
    Column("color", String, nullable=True),
    Column("img_url", String, nullable=True),
    Column("price", Integer, nullable=False),
    Column("stock", Integer, nullable=False),
    Column("is_active", Boolean, nullable=False),
    CheckConstraint("price >= 0", name="ck_product_variants_price_non_negative"),
    Index("ix_product_variants_id", "id"),
    Index("ix_product_variants_sku", "sku", unique=True),
)

discount_products = Table(
    "discount_products",
    metadata,
    Column("discount_id", Integer, ForeignKey("discounts.id", ondelete="CASCADE"), primary_key=True),
    Column("product_id", Integer, ForeignKey("products.id", ondelete="CASCADE"), primary_key=True),
)

orders = Table(
    "orders",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("user_id", Integer, ForeignKey("users.id", ondelete="RESTRICT"), nullable=False),
    Column("status", String, nullable=False),
    Column("currency", String, nullable=False),
    Column("subtotal", Integer, nullable=False),
    Column("discount_total", Integer, nullable=False),
    Column("total_amount", Integer, nullable=False),
    Column("pricing_frozen", Boolean, nullable=False),
    Column("pricing_frozen_at", DateTime(timezone=True), nullable=True),
    Column("submitted_at", DateTime(timezone=True), nullable=True),
    Column("paid_at", DateTime(timezone=True), nullable=True),
    Column("cancelled_at", DateTime(timezone=True), nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
    CheckConstraint("subtotal >= 0", name="ck_orders_subtotal_non_negative"),
    CheckConstraint("discount_total >= 0", name="ck_orders_discount_total_non_negative"),
    CheckConstraint("total_amount >= 0", name="ck_orders_total_amount_non_negative"),
    Index("ix_orders_id", "id"),
)

turns = Table(
    "turns",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("user_id", Integer, ForeignKey("users.id", ondelete="RESTRICT"), nullable=False),
    Column("status", String, nullable=False),
    Column("scheduled_at", DateTime(timezone=True), nullable=True),
    Column("notes", String, nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
    Index("ix_turns_id", "id"),
    Index("ix_turns_user_id", "user_id"),
)

user_refresh_sessions = Table(
    "user_refresh_sessions",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("user_id", Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, unique=True),
    Column("token_hash", String, nullable=False),
    Column("token_jti", String, nullable=False),
    Column("claim_sub", String, nullable=False),
    Column("claim_type", String, nullable=False),
    Column("claim_iss", String, nullable=False),
    Column("claim_iat", DateTime(timezone=True), nullable=False),
    Column("claim_exp", DateTime(timezone=True), nullable=False),
    Column("expires_at", DateTime(timezone=True), nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
    Index("ix_user_refresh_sessions_id", "id"),
    Index("ix_user_refresh_sessions_user_id", "user_id", unique=True),
    Index("ix_user_refresh_sessions_token_jti", "token_jti"),
    Index("ix_user_refresh_sessions_expires_at", "expires_at"),
)

auth_action_tokens = Table(
    "auth_action_tokens",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("user_id", Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False),
    Column("action", String, nullable=False),
    Column("token_hash", String, nullable=False),
    Column("expires_at", DateTime(timezone=True), nullable=False),
    Column("used_at", DateTime(timezone=True), nullable=True),
    Column("requested_ip", String, nullable=True),
    Column("meta", Text, nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Index("ix_auth_action_tokens_id", "id"),
    Index("ix_auth_action_tokens_user_id", "user_id"),
    Index("ix_auth_action_tokens_action", "action"),
    Index("uq_auth_action_tokens_token_hash", "token_hash", unique=True),
    Index("ix_auth_action_tokens_user_action_expires", "user_id", "action", "expires_at"),
    Index("ix_auth_action_tokens_action_expires", "action", "expires_at"),
    Index("ix_auth_action_tokens_used_at", "used_at"),
    Index("ix_auth_action_tokens_expires_at", "expires_at"),
)

order_items = Table(
    "order_items",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("order_id", Integer, ForeignKey("orders.id", ondelete="CASCADE"), nullable=False),
    Column("product_id", Integer, ForeignKey("products.id", ondelete="RESTRICT"), nullable=False),
    Column("variant_id", Integer, ForeignKey("product_variants.id", ondelete="RESTRICT"), nullable=False),
    Column("quantity", Integer, nullable=False),
    Column("unit_price", Integer, nullable=False),
    Column("discount_id", Integer, ForeignKey("discounts.id", ondelete="SET NULL"), nullable=True),
    Column("discount_amount", Integer, nullable=False),
    Column("final_unit_price", Integer, nullable=False),
    Column("line_total", Integer, nullable=False),
    CheckConstraint("quantity > 0", name="ck_order_items_quantity_positive"),
    CheckConstraint("unit_price >= 0", name="ck_order_items_unit_price_non_negative"),
    CheckConstraint("discount_amount >= 0", name="ck_order_items_discount_amount_non_negative"),
    CheckConstraint("final_unit_price >= 0", name="ck_order_items_final_unit_price_non_negative"),
    CheckConstraint("line_total >= 0", name="ck_order_items_line_total_non_negative"),
    Index("ix_order_items_id", "id"),
)

payments = Table(
    "payments",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("order_id", Integer, ForeignKey("orders.id", ondelete="CASCADE"), nullable=False),
    Column("method", String, nullable=False),
    Column("status", String, nullable=False),
    Column("amount", Integer, nullable=False),
    Column("change_amount", Integer, nullable=True),
    Column("currency", String, nullable=False),
    Column("idempotency_key", String, nullable=False, unique=True),
    Column("external_ref", String, nullable=True),
    Column("preference_id", String, nullable=True),
    Column("public_status_token", String, nullable=False),
    Column("provider_status", String, nullable=True),
    Column("provider_payload", String, nullable=True),
    Column("receipt_url", String, nullable=True),
    Column("expires_at", DateTime(timezone=True), nullable=True),
    Column("paid_at", DateTime(timezone=True), nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
    CheckConstraint("amount >= 0", name="ck_payments_amount_non_negative"),
    CheckConstraint("change_amount IS NULL OR change_amount >= 0", name="ck_payments_change_amount_non_negative"),
    Index("ix_payments_id", "id"),
    Index("ix_payments_order_id", "order_id"),
    Index("ix_payments_idempotency_key", "idempotency_key", unique=True),
    Index("ix_payments_external_ref", "external_ref"),
    Index("ix_payments_preference_id", "preference_id"),
    Index("ix_payments_public_status_token", "public_status_token", unique=True),
    Index(
        "uq_payments_one_pending_per_order_method",
        "order_id",
        "method",
        unique=True,
        sqlite_where=text("status = 'pending'"),
        postgresql_where=text("status = 'pending'"),
    ),
)

payment_incidents = Table(
    "payment_incidents",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("order_id", Integer, ForeignKey("orders.id", ondelete="CASCADE"), nullable=False),
    Column("payment_id", Integer, ForeignKey("payments.id", ondelete="CASCADE"), nullable=False),
    Column("type", String, nullable=False),
    Column("status", String, nullable=False),
    Column("reason", Text, nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("resolved_at", DateTime(timezone=True), nullable=True),
    Column("resolved_by_user_id", Integer, ForeignKey("users.id", ondelete="SET NULL"), nullable=True),
    Index("ix_payment_incidents_id", "id"),
    Index("ix_payment_incidents_order_id", "order_id"),
    Index("ix_payment_incidents_payment_id", "payment_id"),
    Index("ix_payment_incidents_type", "type"),
    Index("ix_payment_incidents_status", "status"),
    Index("ix_payment_incidents_resolved_by_user_id", "resolved_by_user_id"),
    Index(
        "uq_payment_incidents_open_per_payment_type",
        "payment_id",
        "type",
        unique=True,
        sqlite_where=text("status = 'pending_review'"),
        postgresql_where=text("status = 'pending_review'"),
    ),
)

payment_refunds = Table(
    "payment_refunds",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("order_id", Integer, ForeignKey("orders.id", ondelete="CASCADE"), nullable=False),
    Column("payment_id", Integer, ForeignKey("payments.id", ondelete="CASCADE"), nullable=False),
    Column("incident_id", Integer, ForeignKey("payment_incidents.id", ondelete="CASCADE"), nullable=False),
    Column("amount", Integer, nullable=False),
    Column("currency", String, nullable=False),
    Column("provider", String, nullable=False),
    Column("provider_refund_id", String, nullable=True),
    Column("status", String, nullable=False),
    Column("idempotency_key", String, nullable=False, unique=True),
    Column("requested_by_user_id", Integer, ForeignKey("users.id", ondelete="RESTRICT"), nullable=False),
    Column("requested_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
    Column("provider_payload", Text, nullable=True),
    CheckConstraint("amount > 0", name="ck_payment_refunds_amount_positive"),
    Index("ix_payment_refunds_id", "id"),
    Index("ix_payment_refunds_order_id", "order_id"),
    Index("ix_payment_refunds_payment_id", "payment_id"),
    Index("ix_payment_refunds_incident_id", "incident_id"),
    Index("ix_payment_refunds_provider_refund_id", "provider_refund_id"),
    Index("ix_payment_refunds_status", "status"),
    Index("ix_payment_refunds_idempotency_key", "idempotency_key", unique=True),
    Index("ix_payment_refunds_requested_by_user_id", "requested_by_user_id"),
    Index(
        "uq_payment_refunds_active_per_payment",
        "payment_id",
        unique=True,
        sqlite_where=text("status IN ('requested','approved')"),
        postgresql_where=text("status IN ('requested','approved')"),
    ),
)

notifications = Table(
    "notifications",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("user_id", Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=True),
    Column("role_target", String, nullable=True),
    Column("event_type", String, nullable=False),
    Column("title", String, nullable=False),
    Column("message", Text, nullable=False),
    Column("order_id", Integer, ForeignKey("orders.id", ondelete="SET NULL"), nullable=True),
    Column("payment_id", Integer, ForeignKey("payments.id", ondelete="SET NULL"), nullable=True),
    Column("incident_id", Integer, ForeignKey("payment_incidents.id", ondelete="SET NULL"), nullable=True),
    Column("dedupe_key", String, nullable=True, unique=True),
    Column("is_read", Boolean, nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("read_at", DateTime(timezone=True), nullable=True),
    Index("ix_notifications_id", "id"),
    Index("ix_notifications_user_id", "user_id"),
    Index("ix_notifications_role_target", "role_target"),
    Index("ix_notifications_event_type", "event_type"),
    Index("ix_notifications_order_id", "order_id"),
    Index("ix_notifications_payment_id", "payment_id"),
    Index("ix_notifications_incident_id", "incident_id"),
    Index("ix_notifications_dedupe_key", "dedupe_key", unique=True),
    Index("ix_notifications_is_read", "is_read"),
    Index("ix_notifications_user_read_created", "user_id", "is_read", "created_at"),
)

stock_reservations = Table(
    "stock_reservations",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("order_id", Integer, ForeignKey("orders.id", ondelete="CASCADE"), nullable=False),
    Column("order_item_id", Integer, ForeignKey("order_items.id", ondelete="CASCADE"), nullable=False),
    Column("variant_id", Integer, ForeignKey("product_variants.id", ondelete="RESTRICT"), nullable=False),
    Column("quantity", Integer, nullable=False),
    Column("status", String, nullable=False),
    Column("reactivation_count", Integer, nullable=False),
    Column("expires_at", DateTime(timezone=True), nullable=False),
    Column("consumed_at", DateTime(timezone=True), nullable=True),
    Column("released_at", DateTime(timezone=True), nullable=True),
    Column("reason", String, nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False),
    Column("updated_at", DateTime(timezone=True), nullable=False),
    CheckConstraint("quantity > 0", name="ck_stock_reservations_quantity_positive"),
    Index("ix_stock_reservations_id", "id"),
    Index("ix_stock_reservations_order_id", "order_id"),
    Index("ix_stock_reservations_order_item_id", "order_item_id"),
    Index("ix_stock_reservations_variant_id", "variant_id"),
    Index("ix_stock_reservations_variant_status_expires", "variant_id", "status", "expires_at"),
    Index("ix_stock_reservations_order_status", "order_id", "status"),
    Index("ix_stock_reservations_status_expires", "status", "expires_at"),
    Index(
        "uq_stock_reservation_active_per_item",
        "order_item_id",
        unique=True,
        sqlite_where=text("status = 'active'"),
        postgresql_where=text("status = 'active'"),
    ),
)

webhook_events = Table(
    "webhook_events",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("provider", String, nullable=False),
    Column("event_key", String, nullable=False, unique=True),
    Column("status", String, nullable=False),
    Column("payload", Text, nullable=True),
    Column("received_at", DateTime(timezone=True), nullable=False),
    Column("processed_at", DateTime(timezone=True), nullable=True),
    Column("last_error", Text, nullable=True),
    Column("attempt_count", Integer, nullable=False),
    Column("next_retry_at", DateTime(timezone=True), nullable=True),
    Column("dead_letter_at", DateTime(timezone=True), nullable=True),
    CheckConstraint("attempt_count >= 0", name="ck_webhook_events_attempt_count_non_negative"),
    Index("ix_webhook_events_id", "id"),
    Index("ix_webhook_events_provider", "provider"),
    Index("ix_webhook_events_event_key", "event_key", unique=True),
    Index("ix_webhook_events_provider_status_retry", "provider", "status", "next_retry_at"),
    Index("ix_webhook_events_dead_letter_at", "dead_letter_at"),
)
